SET LOCAL TIME ZONE 'Asia/Shanghai';

-- Demo groups: one group per provider so model/group/platform filters all have data.
WITH definitions(name, description, platform, rate_multiplier) AS (
    VALUES
        ('demo-claude', 'Demo Anthropic traffic; safe placeholder account', 'anthropic', 1.0000::numeric),
        ('demo-openai', 'Demo OpenAI traffic; safe placeholder account', 'openai', 1.1500::numeric),
        ('demo-gemini', 'Demo Gemini traffic; safe placeholder account', 'gemini', 0.8500::numeric)
)
UPDATE groups AS g
SET description = d.description,
    platform = d.platform,
    rate_multiplier = d.rate_multiplier,
    is_exclusive = FALSE,
    status = 'active',
    deleted_at = NULL,
    updated_at = NOW()
FROM definitions AS d
WHERE g.name = d.name
  AND g.deleted_at IS NULL;

WITH definitions(name, description, platform, rate_multiplier) AS (
    VALUES
        ('demo-claude', 'Demo Anthropic traffic; safe placeholder account', 'anthropic', 1.0000::numeric),
        ('demo-openai', 'Demo OpenAI traffic; safe placeholder account', 'openai', 1.1500::numeric),
        ('demo-gemini', 'Demo Gemini traffic; safe placeholder account', 'gemini', 0.8500::numeric)
)
INSERT INTO groups (name, description, platform, rate_multiplier, is_exclusive, status, created_at, updated_at)
SELECT d.name, d.description, d.platform, d.rate_multiplier, FALSE, 'active', NOW(), NOW()
FROM definitions AS d
WHERE NOT EXISTS (
    SELECT 1
    FROM groups AS g
    WHERE g.name = d.name
      AND g.deleted_at IS NULL
);

-- Demo users. The password hash is generated by the Go command at runtime.
WITH definitions(email, role, balance, concurrency) AS (
    VALUES
        ('demo.admin@sub2api.local', 'admin', 999.00000000::numeric, 20),
        ('demo.ops@sub2api.local', 'user', 80.00000000::numeric, 12),
        ('demo.analyst@sub2api.local', 'user', 65.00000000::numeric, 10),
        ('demo.builder@sub2api.local', 'user', 42.00000000::numeric, 8),
        ('demo.media@sub2api.local', 'user', 28.00000000::numeric, 6)
)
UPDATE users AS u
SET password_hash = '__DEMO_PASSWORD_HASH__',
    role = d.role,
    balance = d.balance,
    concurrency = d.concurrency,
    status = 'active',
    deleted_at = NULL,
    updated_at = NOW()
FROM definitions AS d
WHERE u.email = d.email
  AND u.deleted_at IS NULL;

WITH definitions(email, role, balance, concurrency) AS (
    VALUES
        ('demo.admin@sub2api.local', 'admin', 999.00000000::numeric, 20),
        ('demo.ops@sub2api.local', 'user', 80.00000000::numeric, 12),
        ('demo.analyst@sub2api.local', 'user', 65.00000000::numeric, 10),
        ('demo.builder@sub2api.local', 'user', 42.00000000::numeric, 8),
        ('demo.media@sub2api.local', 'user', 28.00000000::numeric, 6)
)
INSERT INTO users (email, password_hash, role, balance, concurrency, status, created_at, updated_at)
SELECT d.email, '__DEMO_PASSWORD_HASH__', d.role, d.balance, d.concurrency, 'active', NOW(), NOW()
FROM definitions AS d
WHERE NOT EXISTS (
    SELECT 1
    FROM users AS u
    WHERE u.email = d.email
      AND u.deleted_at IS NULL
);

UPDATE users
SET created_at = NOW() - CASE email
    WHEN 'demo.admin@sub2api.local' THEN INTERVAL '14 days'
    WHEN 'demo.ops@sub2api.local' THEN INTERVAL '11 days'
    WHEN 'demo.analyst@sub2api.local' THEN INTERVAL '8 days'
    WHEN 'demo.builder@sub2api.local' THEN INTERVAL '5 days'
    ELSE INTERVAL '2 days'
END
WHERE email LIKE 'demo.%@sub2api.local'
  AND deleted_at IS NULL;

-- Placeholder accounts are never schedulable, so this seed cannot route real requests to fake credentials.
WITH definitions(name, platform, status, priority, error_message) AS (
    VALUES
        ('[DEMO] Anthropic pool', 'anthropic', 'active', 10, NULL::text),
        ('[DEMO] OpenAI pool', 'openai', 'error', 20, 'Demo account: placeholder credentials'),
        ('[DEMO] Gemini pool', 'gemini', 'disabled', 30, 'Demo account: intentionally disabled')
)
UPDATE accounts AS a
SET platform = d.platform,
    type = 'apikey',
    credentials = '{"api_key":"demo-only-not-valid"}'::jsonb,
    extra = '{"seed":"demo","safe_placeholder":true}'::jsonb,
    priority = d.priority,
    status = d.status,
    error_message = d.error_message,
    schedulable = FALSE,
    deleted_at = NULL,
    updated_at = NOW()
FROM definitions AS d
WHERE a.name = d.name
  AND a.deleted_at IS NULL;

WITH definitions(name, platform, status, priority, error_message) AS (
    VALUES
        ('[DEMO] Anthropic pool', 'anthropic', 'active', 10, NULL::text),
        ('[DEMO] OpenAI pool', 'openai', 'error', 20, 'Demo account: placeholder credentials'),
        ('[DEMO] Gemini pool', 'gemini', 'disabled', 30, 'Demo account: intentionally disabled')
)
INSERT INTO accounts (
    name, platform, type, credentials, extra, concurrency, priority, status, error_message,
    schedulable, created_at, updated_at
)
SELECT d.name, d.platform, 'apikey', '{"api_key":"demo-only-not-valid"}'::jsonb,
       '{"seed":"demo","safe_placeholder":true}'::jsonb, 3, d.priority, d.status,
       d.error_message, FALSE, NOW(), NOW()
FROM definitions AS d
WHERE NOT EXISTS (
    SELECT 1
    FROM accounts AS a
    WHERE a.name = d.name
      AND a.deleted_at IS NULL
);

-- One API key per demo user. These are display-only keys and are not connected to real upstream access.
WITH definitions(key_value, name, email, group_name) AS (
    VALUES
        ('sk-demo-admin-0001', 'Demo admin key', 'demo.admin@sub2api.local', 'demo-claude'),
        ('sk-demo-ops-0001', 'Demo operations key', 'demo.ops@sub2api.local', 'demo-openai'),
        ('sk-demo-analyst-0001', 'Demo analyst key', 'demo.analyst@sub2api.local', 'demo-claude'),
        ('sk-demo-builder-0001', 'Demo builder key', 'demo.builder@sub2api.local', 'demo-openai'),
        ('sk-demo-media-0001', 'Demo media key', 'demo.media@sub2api.local', 'demo-gemini')
)
INSERT INTO api_keys (user_id, key, name, group_id, status, created_at, updated_at, deleted_at)
SELECT u.id, d.key_value, d.name, g.id, 'active', NOW(), NOW(), NULL
FROM definitions AS d
JOIN users AS u ON u.email = d.email AND u.deleted_at IS NULL
JOIN groups AS g ON g.name = d.group_name AND g.deleted_at IS NULL
ON CONFLICT (key) DO UPDATE
SET user_id = EXCLUDED.user_id,
    name = EXCLUDED.name,
    group_id = EXCLUDED.group_id,
    status = 'active',
    deleted_at = NULL,
    created_at = EXCLUDED.created_at,
    updated_at = NOW();

UPDATE api_keys
SET created_at = NOW() - CASE key
    WHEN 'sk-demo-admin-0001' THEN INTERVAL '14 days'
    WHEN 'sk-demo-ops-0001' THEN INTERVAL '11 days'
    WHEN 'sk-demo-analyst-0001' THEN INTERVAL '8 days'
    WHEN 'sk-demo-builder-0001' THEN INTERVAL '5 days'
    ELSE INTERVAL '2 days'
END
WHERE key LIKE 'sk-demo-%';

INSERT INTO account_groups (account_id, group_id, priority)
SELECT a.id, g.id, v.priority
FROM (
    VALUES
        ('[DEMO] Anthropic pool', 'demo-claude', 10),
        ('[DEMO] OpenAI pool', 'demo-openai', 20),
        ('[DEMO] Gemini pool', 'demo-gemini', 30)
) AS v(account_name, group_name, priority)
JOIN accounts AS a ON a.name = v.account_name AND a.deleted_at IS NULL
JOIN groups AS g ON g.name = v.group_name AND g.deleted_at IS NULL
ON CONFLICT (account_id, group_id) DO UPDATE
SET priority = EXCLUDED.priority;

-- Remove only rows owned by this seed, making the command safe to run again.
DELETE FROM usage_logs WHERE request_id LIKE 'demo-seed-%';

-- 14 days x 5 users x 3 models = 210 usage rows with varied tokens, costs, endpoints and mappings.
WITH demo_users AS (
    SELECT u.id,
           u.email,
           k.id AS api_key_id,
           ROW_NUMBER() OVER (ORDER BY u.email)::int - 1 AS user_idx
    FROM users AS u
    JOIN api_keys AS k ON k.user_id = u.id
                       AND k.key LIKE 'sk-demo-%'
                       AND k.deleted_at IS NULL
    WHERE u.email LIKE 'demo.%@sub2api.local'
      AND u.deleted_at IS NULL
), model_definitions(model_name, upstream_model, group_name, account_name, inbound_endpoint, upstream_endpoint, model_idx, input_rate, output_rate) AS (
    VALUES
        ('claude-sonnet-4-6', 'claude-sonnet-4-6-20250514', 'demo-claude', '[DEMO] Anthropic pool', '/v1/messages', '/v1/messages', 0, 3.00::numeric, 15.00::numeric),
        ('gpt-4.1', 'gpt-4.1', 'demo-openai', '[DEMO] OpenAI pool', '/v1/chat/completions', '/v1/chat/completions', 1, 2.00::numeric, 8.00::numeric),
        ('gemini-2.5-pro', 'gemini-2.5-pro-preview-05-06', 'demo-gemini', '[DEMO] Gemini pool', '/v1beta/models', '/v1beta/models', 2, 1.25::numeric, 10.00::numeric)
), seed_base AS (
    SELECT
        format('demo-seed-%s-%s-%s', d.day_idx, u.user_idx, m.model_idx) AS request_id,
        u.id AS user_id,
        u.api_key_id,
        a.id AS account_id,
        g.id AS group_id,
        m.model_name,
        m.upstream_model,
        m.inbound_endpoint,
        m.upstream_endpoint,
        m.model_idx,
        d.day_idx,
        (CURRENT_DATE - d.day_idx)::timestamptz
            + CASE
                WHEN d.day_idx = 0 THEN
                    -((5 + u.user_idx * 7 + m.model_idx * 4) * INTERVAL '1 minute')
                ELSE
                    ((8 + ((u.user_idx * 3 + m.model_idx * 2 + d.day_idx) % 10)) * INTERVAL '1 hour')
                    + ((u.user_idx * 11 + m.model_idx * 17 + d.day_idx * 3) % 50) * INTERVAL '1 minute'
              END AS created_at,
        (1900 + d.day_idx * 85 + u.user_idx * 170 + m.model_idx * 260) AS input_tokens,
        (520 + (d.day_idx % 5) * 80 + u.user_idx * 45 + m.model_idx * 95) AS output_tokens,
        (120 + ((d.day_idx + u.user_idx) % 4) * 90) AS cache_creation_tokens,
        (260 + ((d.day_idx + m.model_idx) % 5) * 140) AS cache_read_tokens,
        m.input_rate,
        m.output_rate,
        g.rate_multiplier,
        (d.day_idx + u.user_idx + m.model_idx) % 2 = 0 AS is_stream
    FROM demo_users AS u
    CROSS JOIN model_definitions AS m
    CROSS JOIN generate_series(0, 13) AS d(day_idx)
    JOIN groups AS g ON g.name = m.group_name AND g.deleted_at IS NULL
    JOIN accounts AS a ON a.name = m.account_name AND a.deleted_at IS NULL
), priced AS (
    SELECT *,
           ROUND((input_tokens * input_rate / 1000000.0)::numeric, 10) AS input_cost,
           ROUND((output_tokens * output_rate / 1000000.0)::numeric, 10) AS output_cost,
           ROUND((cache_creation_tokens * input_rate * 1.10 / 1000000.0)::numeric, 10) AS cache_creation_cost,
           ROUND((cache_read_tokens * input_rate * 0.10 / 1000000.0)::numeric, 10) AS cache_read_cost
    FROM seed_base
), totals AS (
    SELECT *,
           ROUND((input_cost + output_cost + cache_creation_cost + cache_read_cost)::numeric, 10) AS total_cost
    FROM priced
)
INSERT INTO usage_logs (
    user_id, api_key_id, account_id, request_id, model, requested_model, upstream_model,
    group_id, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens,
    cache_creation_5m_tokens, cache_creation_1h_tokens,
    input_cost, output_cost, cache_creation_cost, cache_read_cost, total_cost, actual_cost,
    rate_multiplier, account_rate_multiplier, account_stats_cost, billing_type, billing_mode,
    stream, request_type, duration_ms, first_token_ms, inbound_endpoint, upstream_endpoint,
    created_at
)
SELECT
    user_id, api_key_id, account_id, request_id, model_name, model_name, upstream_model,
    group_id, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens,
    cache_creation_tokens, 0,
    input_cost, output_cost, cache_creation_cost, cache_read_cost, total_cost,
    ROUND((total_cost * rate_multiplier)::numeric, 10), rate_multiplier, 1.0000, total_cost,
    0, 'token', is_stream,
    CASE WHEN is_stream THEN 2 ELSE 1 END,
    900 + model_idx * 260 + (day_idx % 6) * 85,
    CASE WHEN is_stream THEN 320 + model_idx * 90 + (day_idx % 5) * 35 ELSE NULL END,
    inbound_endpoint, upstream_endpoint, created_at
FROM totals;

-- Give the API-key and user quota panels meaningful, truthful values derived from the seeded logs.
UPDATE api_keys AS k
SET quota = 25.00000000,
    quota_used = COALESCE((SELECT SUM(ul.actual_cost) FROM usage_logs AS ul WHERE ul.api_key_id = k.id), 0),
    rate_limit_5h = 4.00000000,
    rate_limit_1d = 8.00000000,
    rate_limit_7d = 35.00000000,
    usage_5h = COALESCE((SELECT SUM(ul.actual_cost) FROM usage_logs AS ul WHERE ul.api_key_id = k.id AND ul.created_at >= NOW() - INTERVAL '5 hours'), 0),
    usage_1d = COALESCE((SELECT SUM(ul.actual_cost) FROM usage_logs AS ul WHERE ul.api_key_id = k.id AND ul.created_at >= CURRENT_DATE), 0),
    usage_7d = COALESCE((SELECT SUM(ul.actual_cost) FROM usage_logs AS ul WHERE ul.api_key_id = k.id AND ul.created_at >= CURRENT_DATE - 6), 0),
    last_used_at = (SELECT MAX(ul.created_at) FROM usage_logs AS ul WHERE ul.api_key_id = k.id),
    updated_at = NOW()
WHERE k.key LIKE 'sk-demo-%';

-- Seed per-user platform quotas from the same usage rows used by the dashboards.
WITH demo_users AS (
    SELECT id FROM users WHERE email LIKE 'demo.%@sub2api.local' AND deleted_at IS NULL
), platforms(platform, daily_limit, weekly_limit, monthly_limit) AS (
    VALUES
        ('anthropic', 5.0000000000::numeric, 20.0000000000::numeric, 60.0000000000::numeric),
        ('openai', 6.0000000000::numeric, 24.0000000000::numeric, 72.0000000000::numeric),
        ('gemini', 4.0000000000::numeric, 16.0000000000::numeric, 48.0000000000::numeric)
)
INSERT INTO user_platform_quotas (
    user_id, platform, daily_limit_usd, weekly_limit_usd, monthly_limit_usd,
    daily_usage_usd, weekly_usage_usd, monthly_usage_usd,
    daily_window_start, weekly_window_start, monthly_window_start, created_at, updated_at
)
SELECT u.id, p.platform, p.daily_limit, p.weekly_limit, p.monthly_limit,
       COALESCE((SELECT SUM(ul.actual_cost)
                 FROM usage_logs AS ul
                 JOIN groups AS g ON g.id = ul.group_id
                 WHERE ul.user_id = u.id AND g.platform = p.platform AND ul.created_at >= CURRENT_DATE), 0),
       COALESCE((SELECT SUM(ul.actual_cost)
                 FROM usage_logs AS ul
                 JOIN groups AS g ON g.id = ul.group_id
                 WHERE ul.user_id = u.id AND g.platform = p.platform AND ul.created_at >= CURRENT_DATE - 6), 0),
       COALESCE((SELECT SUM(ul.actual_cost)
                 FROM usage_logs AS ul
                 JOIN groups AS g ON g.id = ul.group_id
                 WHERE ul.user_id = u.id AND g.platform = p.platform AND ul.created_at >= CURRENT_DATE - 29), 0),
       CURRENT_DATE::timestamptz, DATE_TRUNC('week', CURRENT_DATE)::timestamptz, CURRENT_DATE::timestamptz,
       NOW(), NOW()
FROM demo_users AS u
CROSS JOIN platforms AS p
ON CONFLICT (user_id, platform) WHERE deleted_at IS NULL DO UPDATE
SET daily_limit_usd = EXCLUDED.daily_limit_usd,
    weekly_limit_usd = EXCLUDED.weekly_limit_usd,
    monthly_limit_usd = EXCLUDED.monthly_limit_usd,
    daily_usage_usd = EXCLUDED.daily_usage_usd,
    weekly_usage_usd = EXCLUDED.weekly_usage_usd,
    monthly_usage_usd = EXCLUDED.monthly_usage_usd,
    daily_window_start = EXCLUDED.daily_window_start,
    weekly_window_start = EXCLUDED.weekly_window_start,
    monthly_window_start = EXCLUDED.monthly_window_start,
    updated_at = NOW();

-- Rebuild the dashboard aggregates from all logs in the visible window, preserving correctness if real logs already exist.
DELETE FROM usage_dashboard_daily_users WHERE bucket_date >= CURRENT_DATE - 15;
DELETE FROM usage_dashboard_hourly_users WHERE bucket_start >= DATE_TRUNC('hour', NOW() - INTERVAL '15 days');
DELETE FROM usage_dashboard_daily WHERE bucket_date >= CURRENT_DATE - 15;
DELETE FROM usage_dashboard_hourly WHERE bucket_start >= DATE_TRUNC('hour', NOW() - INTERVAL '15 days');

INSERT INTO usage_dashboard_hourly_users (bucket_start, user_id)
SELECT DISTINCT
       DATE_TRUNC('hour', ul.created_at AT TIME ZONE CURRENT_SETTING('TIMEZONE')) AT TIME ZONE CURRENT_SETTING('TIMEZONE'),
       ul.user_id
FROM usage_logs AS ul
WHERE ul.created_at >= NOW() - INTERVAL '15 days'
ON CONFLICT DO NOTHING;

INSERT INTO usage_dashboard_daily_users (bucket_date, user_id)
SELECT DISTINCT
       (hu.bucket_start AT TIME ZONE CURRENT_SETTING('TIMEZONE'))::date,
       hu.user_id
FROM usage_dashboard_hourly_users AS hu
WHERE hu.bucket_start >= DATE_TRUNC('hour', NOW() - INTERVAL '15 days')
ON CONFLICT DO NOTHING;

WITH hourly AS (
    SELECT DATE_TRUNC('hour', ul.created_at AT TIME ZONE CURRENT_SETTING('TIMEZONE')) AT TIME ZONE CURRENT_SETTING('TIMEZONE') AS bucket_start,
           COUNT(*) AS total_requests,
           COALESCE(SUM(ul.input_tokens), 0) AS input_tokens,
           COALESCE(SUM(ul.output_tokens), 0) AS output_tokens,
           COALESCE(SUM(ul.cache_creation_tokens), 0) AS cache_creation_tokens,
           COALESCE(SUM(ul.cache_read_tokens), 0) AS cache_read_tokens,
           COALESCE(SUM(ul.total_cost), 0) AS total_cost,
           COALESCE(SUM(ul.actual_cost), 0) AS actual_cost,
           COALESCE(SUM(COALESCE(ul.account_stats_cost, ul.total_cost) * COALESCE(ul.account_rate_multiplier, 1)), 0) AS account_cost,
           COALESCE(SUM(COALESCE(ul.duration_ms, 0)), 0) AS total_duration_ms
    FROM usage_logs AS ul
    WHERE ul.created_at >= NOW() - INTERVAL '15 days'
    GROUP BY 1
), active_users AS (
    SELECT hu.bucket_start, COUNT(*) AS active_users
    FROM usage_dashboard_hourly_users AS hu
    WHERE hu.bucket_start >= DATE_TRUNC('hour', NOW() - INTERVAL '15 days')
    GROUP BY hu.bucket_start
)
INSERT INTO usage_dashboard_hourly (
    bucket_start, total_requests, input_tokens, output_tokens, cache_creation_tokens,
    cache_read_tokens, total_cost, actual_cost, account_cost, total_duration_ms,
    active_users, computed_at
)
SELECT h.bucket_start, h.total_requests, h.input_tokens, h.output_tokens, h.cache_creation_tokens,
       h.cache_read_tokens, h.total_cost, h.actual_cost, h.account_cost, h.total_duration_ms,
       COALESCE(a.active_users, 0), NOW()
FROM hourly AS h
LEFT JOIN active_users AS a ON a.bucket_start = h.bucket_start
ON CONFLICT (bucket_start) DO UPDATE
SET total_requests = EXCLUDED.total_requests,
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    cache_creation_tokens = EXCLUDED.cache_creation_tokens,
    cache_read_tokens = EXCLUDED.cache_read_tokens,
    total_cost = EXCLUDED.total_cost,
    actual_cost = EXCLUDED.actual_cost,
    account_cost = EXCLUDED.account_cost,
    total_duration_ms = EXCLUDED.total_duration_ms,
    active_users = EXCLUDED.active_users,
    computed_at = NOW();

WITH daily AS (
    SELECT (h.bucket_start AT TIME ZONE CURRENT_SETTING('TIMEZONE'))::date AS bucket_date,
           SUM(h.total_requests) AS total_requests,
           SUM(h.input_tokens) AS input_tokens,
           SUM(h.output_tokens) AS output_tokens,
           SUM(h.cache_creation_tokens) AS cache_creation_tokens,
           SUM(h.cache_read_tokens) AS cache_read_tokens,
           SUM(h.total_cost) AS total_cost,
           SUM(h.actual_cost) AS actual_cost,
           SUM(h.account_cost) AS account_cost,
           SUM(h.total_duration_ms) AS total_duration_ms
    FROM usage_dashboard_hourly AS h
    WHERE h.bucket_start >= DATE_TRUNC('hour', NOW() - INTERVAL '15 days')
    GROUP BY 1
), active_users AS (
    SELECT du.bucket_date, COUNT(*) AS active_users
    FROM usage_dashboard_daily_users AS du
    WHERE du.bucket_date >= CURRENT_DATE - 15
    GROUP BY du.bucket_date
)
INSERT INTO usage_dashboard_daily (
    bucket_date, total_requests, input_tokens, output_tokens, cache_creation_tokens,
    cache_read_tokens, total_cost, actual_cost, account_cost, total_duration_ms,
    active_users, computed_at
)
SELECT d.bucket_date, d.total_requests, d.input_tokens, d.output_tokens, d.cache_creation_tokens,
       d.cache_read_tokens, d.total_cost, d.actual_cost, d.account_cost, d.total_duration_ms,
       COALESCE(a.active_users, 0), NOW()
FROM daily AS d
LEFT JOIN active_users AS a ON a.bucket_date = d.bucket_date
ON CONFLICT (bucket_date) DO UPDATE
SET total_requests = EXCLUDED.total_requests,
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    cache_creation_tokens = EXCLUDED.cache_creation_tokens,
    cache_read_tokens = EXCLUDED.cache_read_tokens,
    total_cost = EXCLUDED.total_cost,
    actual_cost = EXCLUDED.actual_cost,
    account_cost = EXCLUDED.account_cost,
    total_duration_ms = EXCLUDED.total_duration_ms,
    active_users = EXCLUDED.active_users,
    computed_at = NOW();

INSERT INTO usage_dashboard_aggregation_watermark (id, last_aggregated_at, updated_at)
VALUES (1, NOW(), NOW())
ON CONFLICT (id) DO UPDATE
SET last_aggregated_at = EXCLUDED.last_aggregated_at,
    updated_at = NOW();

-- Recent ops data feeds the live throughput, latency, errors and distribution panels.
DELETE FROM ops_error_logs WHERE request_id LIKE 'demo-seed-error-%';

INSERT INTO ops_error_logs (
    request_id, client_request_id, user_id, api_key_id, account_id, group_id, platform, model,
    request_path, stream, error_phase, error_type, severity, status_code, is_business_limited,
    error_message, error_body, error_source, error_owner, account_status, upstream_status_code,
    upstream_error_message, provider_error_code, duration_ms, time_to_first_token_ms,
    auth_latency_ms, routing_latency_ms, upstream_latency_ms, response_latency_ms,
    created_at, inbound_endpoint, upstream_endpoint, requested_model, upstream_model,
    request_type, upstream_errors
)
SELECT
    format('demo-seed-error-%s', s.i),
    format('demo-client-error-%s', s.i),
    u.id, k.id, a.id, g.id, g.platform,
    CASE s.i % 3 WHEN 0 THEN 'claude-sonnet-4-6' WHEN 1 THEN 'gpt-4.1' ELSE 'gemini-2.5-pro' END,
    CASE s.i % 3 WHEN 0 THEN '/v1/messages' WHEN 1 THEN '/v1/chat/completions' ELSE '/v1beta/models' END,
    s.i % 2 = 0,
    CASE s.i % 4 WHEN 0 THEN 'upstream' WHEN 1 THEN 'routing' WHEN 2 THEN 'auth' ELSE 'network' END,
    CASE s.i % 5 WHEN 0 THEN 'rate_limit' WHEN 1 THEN 'overloaded' WHEN 2 THEN 'bad_gateway' WHEN 3 THEN 'invalid_request' ELSE 'timeout' END,
    CASE s.i % 5 WHEN 0 THEN 'P2' WHEN 3 THEN 'P3' ELSE 'P1' END,
    CASE s.i % 5 WHEN 0 THEN 429 WHEN 1 THEN 529 WHEN 2 THEN 502 WHEN 3 THEN 400 ELSE 504 END,
    s.i % 5 = 0,
    CASE s.i % 5 WHEN 0 THEN 'Demo rate limit sample' WHEN 1 THEN 'Demo upstream overloaded sample' WHEN 2 THEN 'Demo provider gateway sample' WHEN 3 THEN 'Demo validation sample' ELSE 'Demo timeout sample' END,
    '{"demo":true,"safe_placeholder":true}',
    CASE WHEN s.i % 5 IN (0, 3) THEN 'gateway' ELSE 'upstream_http' END,
    CASE WHEN s.i % 5 = 0 THEN 'platform' ELSE 'provider' END,
    CASE s.i % 3 WHEN 0 THEN 'active' WHEN 1 THEN 'error' ELSE 'disabled' END,
    CASE s.i % 5 WHEN 0 THEN 429 WHEN 1 THEN 529 WHEN 2 THEN 502 ELSE 500 END,
    CASE s.i % 5 WHEN 0 THEN 'demo upstream rate limit' WHEN 1 THEN 'demo upstream overloaded' ELSE 'demo upstream unavailable' END,
    CASE s.i % 5 WHEN 0 THEN 'rate_limit' WHEN 1 THEN 'overloaded' ELSE 'upstream_error' END,
    850 + (s.i % 7) * 180,
    300 + (s.i % 5) * 70,
    12 + (s.i % 4) * 4,
    18 + (s.i % 5) * 6,
    420 + (s.i % 7) * 95,
    920 + (s.i % 6) * 160,
    NOW() - (s.i * INTERVAL '4 hours') - ((s.i % 3) * INTERVAL '17 minutes'),
    CASE s.i % 3 WHEN 0 THEN '/v1/messages' WHEN 1 THEN '/v1/chat/completions' ELSE '/v1beta/models' END,
    CASE s.i % 3 WHEN 0 THEN '/v1/messages' WHEN 1 THEN '/v1/chat/completions' ELSE '/v1beta/models' END,
    CASE s.i % 3 WHEN 0 THEN 'claude-sonnet-4-6' WHEN 1 THEN 'gpt-4.1' ELSE 'gemini-2.5-pro' END,
    CASE s.i % 3 WHEN 0 THEN 'claude-sonnet-4-6-20250514' WHEN 1 THEN 'gpt-4.1' ELSE 'gemini-2.5-pro-preview-05-06' END,
    CASE WHEN s.i % 2 = 0 THEN 2 ELSE 1 END,
    CASE WHEN s.i % 4 = 0 THEN '[{"kind":"failover:account","status":529}]'::jsonb ELSE '[]'::jsonb END
FROM generate_series(0, 17) AS s(i)
CROSS JOIN LATERAL (
    SELECT u0.id
    FROM users AS u0
    WHERE u0.email = 'demo.analyst@sub2api.local' AND u0.deleted_at IS NULL
    LIMIT 1
) AS u
CROSS JOIN LATERAL (
    SELECT k0.id
    FROM api_keys AS k0
    WHERE k0.key = 'sk-demo-analyst-0001' AND k0.deleted_at IS NULL
    LIMIT 1
) AS k
JOIN groups AS g ON g.name = CASE s.i % 3 WHEN 0 THEN 'demo-claude' WHEN 1 THEN 'demo-openai' ELSE 'demo-gemini' END
                AND g.deleted_at IS NULL
JOIN accounts AS a ON a.name = CASE s.i % 3 WHEN 0 THEN '[DEMO] Anthropic pool' WHEN 1 THEN '[DEMO] OpenAI pool' ELSE '[DEMO] Gemini pool' END
                  AND a.deleted_at IS NULL;

DELETE FROM ops_system_metrics
WHERE group_id IN (SELECT id FROM groups WHERE name LIKE 'demo-%' AND deleted_at IS NULL)
  AND created_at >= NOW() - INTERVAL '4 days';

INSERT INTO ops_system_metrics (
    created_at, window_minutes, platform, group_id, success_count, error_count_total,
    business_limited_count, error_count_sla, upstream_error_count_excl_429_529,
    upstream_429_count, upstream_529_count, token_consumed, qps, tps,
    duration_p50_ms, duration_p90_ms, duration_p95_ms, duration_p99_ms,
    duration_avg_ms, duration_max_ms, ttft_p50_ms, ttft_p90_ms, ttft_p95_ms,
    ttft_p99_ms, ttft_avg_ms, ttft_max_ms, cpu_usage_percent, memory_used_mb,
    memory_total_mb, memory_usage_percent, db_ok, redis_ok, db_conn_active,
    db_conn_idle, db_conn_waiting, goroutine_count, concurrency_queue_depth
)
SELECT
    NOW() - (s.i * INTERVAL '1 hour'), 1, g.platform, g.id,
    150 + ((s.i + g.id) % 38),
    4 + ((s.i + g.id) % 8),
    1 + (s.i % 2),
    3 + ((s.i + g.id) % 6),
    1 + (s.i % 3),
    1 + (s.i % 2),
    s.i % 3,
    25000 + ((s.i + g.id) % 16) * 1100,
    ROUND((2.4 + (s.i % 5) * 0.18)::numeric, 2)::double precision,
    ROUND((820.0 + (s.i % 7) * 42.0)::numeric, 2)::double precision,
    420 + (s.i % 6) * 28,
    760 + (s.i % 7) * 46,
    980 + (s.i % 8) * 55,
    1450 + (s.i % 9) * 80,
    (610.0 + (s.i % 5) * 31.0)::double precision,
    1900 + (s.i % 7) * 120,
    260 + (s.i % 6) * 25,
    410 + (s.i % 7) * 31,
    590 + (s.i % 8) * 38,
    880 + (s.i % 9) * 54,
    (360.0 + (s.i % 5) * 24.0)::double precision,
    1200 + (s.i % 7) * 95,
    (28.0 + (s.i % 6) * 3.2)::double precision,
    4200 + (s.i % 5) * 180,
    8192,
    (51.0 + (s.i % 5) * 2.2)::double precision,
    TRUE, TRUE,
    6 + (s.i % 4), 24 - (s.i % 4), s.i % 2, 80 + (s.i % 11), s.i % 6
FROM generate_series(0, 71) AS s(i)
CROSS JOIN groups AS g
WHERE g.name LIKE 'demo-%'
  AND g.deleted_at IS NULL;
